services:
  ollama:
    image: ollama/ollama:0.18.3
    container_name: ollama
    hostname: ollama
    restart: always
    ports:
      - "127.0.0.1:11436:11434"
    entrypoint: ["ollama", "serve"]
    volumes:
      - ./models/:/models
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}  # keep models loaded in memory for faster response
      - OLLAMA_NUM_THREADS=${OLLAMA_NUM_THREADS}      # limit CPU usage, keep host responsive
      - OLLAMA_MAX_CTX=${OLLAMA_MAX_CTX}       # small context window reduces chance of long unsafe runs
      - OLLAMA_DISABLE_WHITELIST=${OLLAMA_DISABLE_WHITELIST}  # we'll add our own whitelist (see 4)
    deploy:
      resources:
        limits:
          cpus: ${OLLAMA_CPUS}  # limit to 2 CPU cores by default
          memory: ${OLLAMA_MEMORY}

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.8.12
    container_name: open-webui
    restart: always
    ports:
      - "8282:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}

  nginx:
    image: nginx:1.29.7-alpine-slim
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ollama
      - open-webui

volumes:
  ollama_data:
  open-webui:

networks:
  default:
    name: ollama-network
    driver: bridge
